stages:
  - mavenbuild
  - maventest
  - mavendeploy

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag          # <-- tag of your VM/backend runner
  script:
    - cd Backend/springboot_manytoone
    - mvn -B package
  artifacts:
    paths:
      - Backend/springboot_manytoone/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - springboot_tag          # <-- same VM/backend runner
  script:
    - cd Backend/springboot_manytoone
    - mvn -B test
  only:
    refs:
      - main
    changes:
      - Backend/**/*

auto-deploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/springboot_manytoone
    - mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main
    changes:
      - Backend/**/*