stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild
  tags:
    - shell            # <-- use your LOCAL runner tag here
  script:
    - cd Backend/springboot_manytoone
    - mvn package
  artifacts:
    paths:
      - Backend/springboot_manytoone/target/*.jar
  only:
    refs:
      - trungly_backend    # <-- your local branch name
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - shell            # <-- same local runner tag
  script:
    - cd Backend/springboot_manytoone
    - mvn test
  only:
    refs:
      - trungly_backend    # <-- your local branch name
    changes:
      - Backend/**/*