stages:
  - mavenbuild
  - maventest
  - mavendeploy

maven-build:
  stage: mavenbuild
  tags:
    - trungly_tag            # <-- YOUR LOCAL MAC RUNNER
  script:
    - cd Backend/springboot_manytoone
    - mvn -B package
  artifacts:
    paths:
      - Backend/springboot_manytoone/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/**/*

maven-test:
  stage: maventest
  tags:
    - trungly_tag
  script:
    - cd Backend/springboot_manytoone
    - mvn -B test
  only:
    refs:
      - main
    changes:
      - Backend/**/*

auto-deploy:
  stage: mavendeploy
  tags:
    - trungly_tag
  script:
    - cd Backend/springboot_manytoone
    - mkdir -p deploy
    - cp target/*.jar deploy/web-demo.jar
    - echo "Deploy complete (local copy only)"
  only:
    refs:
      - main
    changes:
      - Backend/**/*